// Regenerates PROJECT-EXPORT.md: AGENTS.md followed by every source file inline.
// Run with: node scripts/export-context.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, extname } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const FILES = [
  'package.json',
  'vite.config.ts',
  'tsconfig.json',
  'index.html',
  'src/main.tsx',
  'src/App.tsx',
  'src/data/content.ts',
  'src/icons.ts',
  'src/lib/motion.ts',
  'src/index.css',
  '.github/workflows/deploy.yml',
]

const LANG = { '.ts': 'ts', '.tsx': 'tsx', '.css': 'css', '.html': 'html', '.json': 'json', '.yml': 'yaml' }

const parts = [
  '# Portfolio — full project context\n',
  '> Generated by `scripts/export-context.mjs`. Hand this single file to a new agent or',
  '> session for complete context: architecture notes first, then every source file verbatim.\n',
  '---\n',
  readFileSync(join(root, 'AGENTS.md'), 'utf8').replace(/^# /, '## '),
  '\n---\n',
  '## Source files\n',
  'Binary assets are not inlined. `public/images/` holds `profile-{96,192,288}.{avif,webp}`',
  'plus `profile-192.jpg` (square, rendered as a 96px circle), and `public/favicon.svg`.\n',
]

for (const rel of FILES) {
  const abs = join(root, rel)
  if (!existsSync(abs)) {
    parts.push(`### \`${rel}\`\n\n_(missing)_\n`)
    continue
  }
  const body = readFileSync(abs, 'utf8').trimEnd()
  parts.push(`### \`${rel}\`\n`, '```' + (LANG[extname(rel)] ?? ''), body, '```\n')
}

const out = parts.join('\n')
writeFileSync(join(root, 'PROJECT-EXPORT.md'), out)
console.log(`PROJECT-EXPORT.md written — ${FILES.length} files, ${(out.length / 1024).toFixed(1)} kB`)
